# Generated by Django 5.2.3 on 2025-10-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_populate_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
